# Name of the snippet:
TARGET_NAME = day02

# Specify all source files:
SOURCES = main.c
SOURCES += record_access.c

# Specify all include paths:
INCLUDES = -I.
#INCLUDES += ...

# Specify defines:
DEFINES =
#DEFINES += ...

include ../global.mk
